export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'contentful',
        'shopify',
        'okendo',
        'adapter-nextjs',
        'cache',
        'types',
        'docs',
        'deps',
        'release',
        'config',
        'codegen',
      ],
    ],
    'body-max-line-length': [2, 'always', 200],
    'header-max-length': [2, 'always', 72],
  },
};
